In [181]:
import numpy as np
import pandas as pd
traindata=np.loadtxt("bostontrain.csv",delimiter=",")
testdata=np.loadtxt("bostontest.csv",delimiter=",")
traindata

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011, 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412, 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588, 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299, 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218, 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335, 50.        ]])

In [182]:
from sklearn.ensemble import GradientBoostingRegressor
alg=GradientBoostingRegressor()
x=traindata[:,:-1]
y=traindata[:,-1]
alg.fit(x,y)


GradientBoostingRegressor()

In [97]:
normpred=alg.predict(testdata)                     #prediction using Gradient Descent algo
normpred

array([11.71762886, 26.80499145, 17.09852907, 22.06512279, 21.19058003,
       12.2832724 , 29.43944575, 25.20237061, 18.77275134, 22.99272373,
       23.39058111, 17.6291958 , 19.64676654, 20.8280366 , 51.86380438,
       21.03836143, 23.49131107, 22.87310447, 19.17816831, 30.68495565,
       20.89789526, 21.49588187, 36.62299579, 31.39775722, 33.27921713,
       16.38574194, 20.47642029, 30.64770333, 19.97381035, 28.7847961 ,
       17.218498  , 24.68879147, 20.79190642, 22.83448526,  8.58056865,
       23.80896034, 22.57697789, 20.44057093, 22.71189925,  8.0482711 ,
       14.97739569, 23.59244202, 24.78663662, 19.90148152, 21.80376912,
        9.75039457, 43.705159  , 24.57774682, 34.08549728, 12.83411894,
       14.06393226, 45.23318763, 14.38762866, 20.95608777, 17.02834623,
       19.69745011, 18.88744499, 22.4778254 , 15.32494152, 15.84899874,
       13.68437009, 27.27249687, 22.29881719, 23.0038954 , 14.49435547,
       16.20543174, 32.88520177, 12.57183546, 20.91664926, 21.38

In [183]:
def gd(dataval,alpha,num_iteration):
    m=np.zeros(dataval.shape[1])
    for i in range(num_iteration):
        m=stepgrad(dataval,alpha,m)
    print("Cost=", cost(dataval,m))
    return m

In [184]:
def stepgrad(dataval,alpha,m):
    N=dataval.shape[0]
    updated_m=np.zeros(dataval.shape[1])
    for i in range(N):
        x=dataval[i,:-1]
        x=np.append(x,1)
        y=dataval[i,-1]
        for j in range(dataval.shape[1]):
            updated_m[j] += (-2/N)*(y-(m*x).sum())*x[j]
        m=m-(alpha*updated_m[j])
    return m

In [186]:
def cost(dataval, m):
    costval = 0
    N = dataval.shape[0]
    for i in range(N):
        x = dataval[i,:-1]
        x = np.append(x, 1)
        y = dataval[i,-1]
        costval +=(1/N)* ((y-(m*x).sum())**2)
        
    return float(costval)

In [190]:
def run():
    alpha=0.0001
    num_iteration=1000
    M=gd(traindata,alpha,num_iteration)
    m=M[0:13]
    c=M[13]
    return m,c

In [191]:
m,c=run()
print(m,c)

Cost= 6260.487600382911
[16.6223927 16.6223927 16.6223927 16.6223927 16.6223927 16.6223927
 16.6223927 16.6223927 16.6223927 16.6223927 16.6223927 16.6223927
 16.6223927] 16.622392704879545


In [179]:
new= [0]*(traindata[:,:-1].shape[1])

In [180]:
new

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [131]:
def predict(dataval, m, c):
    N = dataval.shape[0]
    y = np.zeros(N)
    for i in range(N):                               #prediction using m ,c ,alpha and numof iterations 
        X = dataval[i,:]
        y[i] = (m * X).sum() + c
    return y

In [132]:
testpred=predict(testdata,m,c)
testpred

array([ 1.16667855e+01,  2.86344650e+01,  2.24875449e+01,  2.45638599e+01,
        2.12047366e+01,  3.06429042e+00,  3.04607609e+01,  2.51178821e+01,
        1.89887971e+01,  2.38316431e+01,  2.44628299e+01,  1.80264361e+01,
        1.80249177e+01,  2.16804187e+01,  4.11684742e+01,  2.40459774e+01,
        2.46727936e+01,  2.78257201e+01,  2.05102047e+01,  3.12676626e+01,
        2.39657315e+01,  2.41494696e+01,  3.30019710e+01,  3.58811061e+01,
        3.22003819e+01,  1.62568376e+01,  2.34931190e+01,  3.30110104e+01,
        2.43541148e+01,  3.32078637e+01,  1.72993664e+01,  2.62059792e+01,
        2.35458858e+01,  2.53964111e+01,  1.48509930e+01,  2.95737100e+01,
        2.64678686e+01,  2.07264731e+01,  2.42591530e+01,  9.53685240e+00,
        7.82824548e+00,  2.90715532e+01,  2.95691947e+01,  1.95830816e+01,
        2.02748558e+01,  3.06038850e+00,  3.95587657e+01,  2.56479655e+01,
        3.05027626e+01,  1.68548164e+01,  1.76073795e+01,  4.07057045e+01,
        1.75940346e+01,  

In [133]:
np.savetxt("bostonpred.csv",testpred,fmt='%f')

In [19]:
from sklearn import preprocessing
scale=preprocessing.StandardScaler()
val1=traindata
scale.fit(val1)
val1=scale.transform(val1)
scaledtrainy=val1[:,-1] # scaled training data output 
scaledtrainy

array([ 1.63059527e+00, -1.28982221e-01, -1.05675944e+00, -2.88943812e-01,
       -1.16770554e-02,  1.07606176e+00,  6.29716867e-02, -1.18318115e-01,
       -2.24959176e-01,  1.14004639e+00,  5.23075807e-02, -2.78279706e-01,
        2.92095210e+00,  2.54925595e-01, -2.56951494e-01, -6.62187522e-01,
       -2.23411614e-02, -2.35623282e-01, -4.48905402e-01,  1.56661063e+00,
        5.23075807e-02,  1.28934388e+00,  1.11871818e+00,  6.49497517e-01,
       -7.47500370e-01, -4.70233614e-01, -5.76874674e-01,  9.48092485e-01,
        4.25551291e-01,  1.58948641e-01, -3.30052674e-02, -3.31600236e-01,
        1.43864136e+00, -5.34218250e-01,  1.15071050e+00, -1.47265958e+00,
       -1.37668262e+00, -9.82110702e-01,  1.83321328e+00,  1.90940959e-01,
       -5.12890038e-01,  1.80276853e-01,  1.48284535e-01,  5.23075807e-02,
       -1.01410302e+00, -6.30195204e-01,  2.03152626e-02,  5.21528245e-01,
       -8.54141430e-01, -9.82110702e-01, -1.23804925e+00, -3.42264342e-01,
       -8.11485006e-01,  

In [41]:
testtrain=val1[:,:-1]
ans=predict(testtrain,m,c)
ans=ans.reshape(-1,1)           #prediction of training data using gradient descent and then scaling 
scale.fit(ans)
scaledtrainpred=scale.transform(ans)
scaledtrainpred.reshape(-1)

array([ 1.43087158e+00,  2.51680207e-01, -1.13385810e+00, -4.52930291e-01,
        2.61923444e-02,  1.09644341e+00, -6.02235948e-02, -2.26290884e-01,
       -2.65573934e-01,  1.72925857e+00,  3.56355332e-01,  8.82803423e-02,
        2.55579347e+00,  3.55232712e-01, -2.60185459e-02, -4.33835024e-01,
       -5.78200546e-05, -2.74815968e-01, -3.29976442e-01,  1.33068611e+00,
       -1.26380500e-01,  1.06298529e+00,  1.49354629e+00,  4.72809254e-01,
       -2.15051950e-01, -3.32957927e-01, -1.19739162e+00,  1.30913013e+00,
        7.78443984e-01,  8.71268601e-01,  4.66883632e-01, -3.68366447e-01,
        1.27013839e+00, -7.01114956e-01,  1.52530519e+00, -2.03659942e+00,
       -1.65699370e+00, -1.06662757e+00,  1.51387830e+00,  1.44164421e-01,
       -6.11455799e-01,  7.73872497e-01,  3.83123488e-01, -1.38588235e+00,
       -9.95713053e-01, -3.96931475e-01,  5.83921993e-01,  3.30515521e-01,
       -1.81518732e+00, -1.13011132e+00, -1.00146121e+00, -2.95361283e-01,
       -4.39799472e-01,  

In [54]:
def score(scaledtrainy,scaledpredy):                                    #comparing of actualtraining data output 
    u=((scaledtrainy-scaledpredy)**2).sum()                             #and output predicted of training data
    v=((scaledtrainy-scaledtrainy.mean())**2).sum()
    return 1- u/v  

In [55]:
scaledpredy=scaledtrainpred.reshape(-1)
score(scaledtrainy,scaledpredy)

0.7087110811829032